import { Inter } from "next/font/google";
import "./globals.scss";
import CustomProvider from "@/src/utils/provider";
import DarkLightMode from "@/src/components/darkLightMode";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CustomProvider>
          <DarkLightMode />
          {children}
        </CustomProvider>
      </body>
    </html>
  );
}
